server {
    listen 80;
    server_name studentcare.site www.studentcare.site;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name studentcare.site www.studentcare.site;

    ssl_certificate /etc/ssl/cloudflare/api.studentcare.site.pem;
    ssl_certificate_key /etc/ssl/cloudflare/api.studentcare.site.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    return 301 https://studentcare.site$request_uri;
}
